name:
  sample-job

components:
  - class:
      YourSpoutClass
    module:
      YourModuleName
    type:
      spout
  - class:
      YourBoltClass
    module:
      YourModuleName
    grouping:
      SHUFFLE
    type:
      bolt
